### PR TITLE
Adding documentation (Sphinx) and docstrings

### PR DESCRIPTION
**Pull request by kallewesterling**
This PR includes a lot of edits:
- Moving of the old documentation to a separate folder (then entirely removed)
- Adding in Sphinx + theme ([sphinx-book-theme](https://sphinx-book-theme.readthedocs.io/en/stable/index.html)) and plug-ins needed (described in `docs/requirements.txt`
- Adding all the documentation from former `docs` folder (markdown) into new format (RST) in the new `docs` directory
- Adding in docstrings (or placeholders for some docstrings) for most methods and functions across the codebase.

### CODE REVIEW

**Comment by edwardchalstrey1** [comment]
Thanks @kallewesterling this looks great! I'll have a proper review at some point next week I think. In the meantime I'll use today's Seshat meeting to check on Majid's progress with merging the work on this fork so far to the upstream repo and updating the production site. Until that's done I've been avoiding editing parts of the code that aren't directly related to the maps, but I'm hopeful we'll be at that point very soon and can do things like this updating his docstrings etc and do more regular PRs to avoid large conflicts

**Comment by edwardchalstrey1** [comment]
Hi @kallewesterling I've just had a go at checking this out locally and building the docs (and aim to look at the conflicts next). I've added `sphinx-rtd-theme` which seems to be required: https://github.com/kallewesterling/seshat/pull/1 (in future feel free to use my repo instead of your fork when making branches/PRs)

~~On building the docs I'm currently getting these errors (and it seems to be either hanging now or just taking a very long time) - this all comes after `[AutoAPI] Reading files... [100%]`~~ **Update:** this was caused by me having a venv for Pulumi in the directory structure

**Comment by edwardchalstrey1** [comment]
~~Actually perhaps I should try setting up a new python env specifically for docs as the error seems to be caused by Pulumi~~ A new Python env was not required

**Comment by edwardchalstrey1** [comment]
Ok nice, docs building for me now - will have a proper review tomorrow 👍

**Comment by kallewesterling** [comment]
Great to hear!! Let me know if you run into any other problems!

**Comment by edwardchalstrey1** [comment]
I have opened a new issue #175 to ensure tests can be run by actions in future, but for now I have confirmed tests run locally so will merge

**Pull request merged**
